name: Azure Static Web Apps prod CI/CD

on:
  push:
    branches:
      - master

jobs:
  build_release_job:
    name: Build SWA
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true
        lfs: false
    - name: Install dependencies
      run: yarn add
    - name: Build project
      run: yarn build
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Static Web App
        path: dist/
